name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Copy Files to Azure VM
        uses: appleboy/scp-action@v0.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: |
            backend/*
            frontend/dist/*
          target: ~/deployment

      - name: Deploy on Azure VM and Capture Log
        uses: appleboy/ssh-action@v0.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            {
              cd ~/deployment/backend
              npm install
              pm2 restart app.js || pm2 start app.js
              cp -r ~/deployment/frontend/dist/* /var/www/html/
              sudo systemctl reload nginx
              echo "Deployment finished on $(date)"
            } &> ~/deployment/deploy.log
